apiVersion: v1
kind: ConfigMap
metadata:
  name: rhdh-github-appconfig
  namespace: rhdh-operator
data:
  app-config.yaml: |
    app:
      baseUrl: https://backstage-developer-hub-rhdh-operator.apps.xps.planenotsimple.com

    backend:
      baseUrl: https://backstage-developer-hub-rhdh-operator.apps.xps.planenotsimple.com
      cors:
        origin: https://backstage-developer-hub-rhdh-operator.apps.xps.planenotsimple.com

    auth:
      environment: production
      providers:
        github:
          production:
            clientId: ${AUTH_GITHUB_CLIENT_ID}
            clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
            signIn:
              resolvers:
                - resolver: usernameMatchingUserEntityName

    catalog:
      locations:
        - type: file
          target: /app-config/users.yaml
          rules:
            - allow: [User, Group]
        - type: url
          target: https://raw.githubusercontent.com/brentnjones/wordpress-plugins-as-code/main/templates/wordpress-install/template.yaml
          rules:
            - allow: [Template]

    kubernetes:
      clusterLocatorMethods: []
