apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: wordpress-install-template
spec:
  type: url
  target: https://raw.githubusercontent.com/brentnjones/wordpress-plugins-as-code/main/templates/wordpress-install/template.yaml
